### PR TITLE
Integrate SpanMarker with API Inference + Tests

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull Request overview
* Integrate [SpanMarker for Named Entity Recognition](https://github.com/tomaarsen/SpanMarkerNER) into API Inference
  * [x] Copied `docker_images/common`.
  * [x] Edited `docker_images/span_marker/requirements.txt`, `docker_images/span_marker/main.py` and `docker_images/span_marker/pipelines/token_classification.py`.
  * [x] Removed unused pipeline files, tests and imports.
  * [x] Edited `span_marker/tests/test_api.py` with a `bert-tiny` model for quick tests.
  * [x] Edited `tests/test_dockers.py` with a new test for `def test_span_marker(self)`.

## Details
[SpanMarker](https://github.com/tomaarsen/SpanMarkerNER) is a model architecture for Named Entity Recognition that is tightly implemented on top of transformers. As you can see in `docker_images/span_marker/app/pipelines/token_classification.py`, it's a very easy implementation as a result.

Feel free to play with this this [Space](https://huggingface.co/spaces/tomaarsen/span-marker-bert-base-fewnerd-fine-super) to get a feel for the power of the architecture.

I've used my [`tomaarsen/span-marker-bert-tiny-fewnerd-coarse-super`](https://huggingface.co/tomaarsen/span-marker-bert-tiny-fewnerd-coarse-super) model throughout the tests. This model is based on the `bert-tiny` encoder, trained on supervised, coarse-grained [FewNERD](https://huggingface.co/datasets/DFKI-SLT/few-nerd). 
This should allow the tests to continue to be smooth, as the model is only ~18MB in total.

To the best of my knowledge, I've followed all of the steps in the README and from the [integration documentation](https://huggingface.co/docs/hub/models-adding-libraries). Please let me know if you need anything else from me at this point!

- Tom Aarsen

### CODE REVIEW

**Comment by tomaarsen** [comment]
On a slightly related note - once I know that this is indeed all I have to update to integrate a library, I can certainly integrate 🤗 [SetFit](https://github.com/huggingface/setfit) fully.

**Comment by Narsil** [comment]
This is indeed all the required steps. We can also add some github action for testing and deploying this automatically. (I can take care of that, it make subsequent maintenance much easier)

@osanseviero could you share your input here ?

**Review by osanseviero — APPROVED** [review]
The PR Looks good! 

Feel free to also add GitHub action workflows to automatize tests and CD
* https://github.com/huggingface/api-inference-community/blob/main/.github/workflows/python-api-fasttext-cd.yaml 
* https://github.com/huggingface/api-inference-community/blob/main/.github/workflows/python-api-fasttext.yaml

**Comment by tomaarsen** [comment]
Done! I've updated the files based on all the other workflows. I can't test these workflows locally, so I hope they look good. We'll wait for https://github.com/huggingface/hub-docs/pull/737 before merging this 👍 

- Tom Aarsen

**Comment by tomaarsen** [comment]
I'll be drafting this until a full v1.0.0 release for SpanMarker as discussed in https://github.com/huggingface/hub-docs/pull/737!

**Comment by Narsil** [comment]
Any news, the PR is in a good state, tell me whenever you would like it to be merged !

**Comment by tomaarsen** [comment]
I'll let you know when it's ready! :)

**Comment by tomaarsen** [comment]
[SpanMarker](https://github.com/tomaarsen/SpanMarkerNER) just released with v1.0.0, so I'm ready to get this integration merged!

**Review by osanseviero — APPROVED** [review]
Looks great!

**Comment by osanseviero** [comment]
I'll let @Narsil have a final look and then we can merge ahead

**Review by Narsil — APPROVED** [review]
Lgtm

**Pull request merged**
