### PR TITLE
Fixing pyannote.audio integration

### PR DESCRIPTION
**Pull request by hbredin**
pyannote.audio integration seems to be broken: models takes forever to load, ending up in a time out.

This is a (desperate) attempt at fixing this...

image

### CODE REVIEW

**Comment by hbredin** [comment]
Looks like one Docker test is failing (that used to not fail)...

DockerImageTests.test_pyannote ________________________

self = <test_dockers.DockerImageTests testMethod=test_pyannote>

```
    def test_pyannote(self):
>       self.framework_docker_test(
            "pyannote",
            "automatic-speech-recognition",
            "pyannote/voice-activity-detection",
        )
E       TypeError: framework_docker_test() missing 1 required positional argument: 'custom_input'
```

I have no idea what this `custom_input` should be...

**Comment by osanseviero** [comment]
Sorry, that was an unrelated bug. I just did a commit to see if it fixes the issue

**Comment by Narsil** [comment]
Oh the issue is that the docker image is not found because it's misconfigured. 

I think this is because the library_name of the hub is `pyannote_audio` and not `pyannote`  (here in this library it's defined as `pyannote`.)

**Comment by Narsil** [comment]
It's working now ! https://huggingface.co/pyannote/speaker-diarization

**Comment by hbredin** [comment]
Thanks a lot for the quick fix!

**Pull request merged**
