### PR TITLE
Follow-up: increment hf_hub for Sentence Transformers

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull Request overview
* Also increment `huggingface_hub` for Sentence Transformers

## Details
Apologies, forgot to increment this one alongside #381.

cc @osanseviero 

- Tom Aarsen

### CODE REVIEW

**Review by Narsil — APPROVED** [review]
LGTM

**Review by osanseviero — APPROVED** [review]

**Comment by tomaarsen** [comment]
Let me chase down the test failure

**Comment by Narsil** [comment]
@tomaarsen don't dive too much. If it works locally for you, this one could be just the CI having issues with docker which sometime happens (only if it passes locally)

**Comment by tomaarsen** [comment]
@Narsil No, I don't have a test pass locally, but that is because the test suite does not work on Windows as far as I can tell. I receive `httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it` for Sentence Transformers as well as e.g. SpanMarker.
I've been able to run it with `python manage.py start` though.

**Comment by osanseviero** [comment]
In my experience it's usually to some time-outs/test flakiness we need to fix. Let's merge ahead :)

**Pull request merged**
