### PR TITLE
Adding negative_prompt to diffusers.

### LINKED ISSUE #185: Enable negative_prompt param on text-to-image pipeline
Since `StableDiffusion` and `AltDiffusion`  supports negative prompting, it would be great to have it enable on the Inference API. Specially important on [Stable Diffusion v2](https://minimaxir.com/2022/11/stable-diffusion-negative-prompt/)

### PR DESCRIPTION
**Pull request by Narsil**
Fixes #185

### CODE REVIEW

**Comment by apolinario** [comment]
LGTM! The only question is: would we be able (or want to) modify the inference widget to also support negative prompts?

If not, an alternative way to do it would be to use a single field but with special characters to split what is the prompt and what is the negative prompt (e.g.: Midjourney uses `::` for multi-prompting)

**Comment by Narsil** [comment]
For the widget we would need @mishig25 advice.

The widget is the same for ALL `text-to-image` models.

If you're ok with using `::` we could remove the parameter here, and simply use it here, wdyt ?

That makes everything work in the widget out-of-the-box. Just this `::` might not be intuitive nor discoverable..

**Comment by apolinario** [comment]
I think we could keep both. The two inputs for the actual API and the parsing for the widget (but no need to make this distinction, just check if there's a `::` in the prompt and if so use that as a negative prompt)

I do agree with the intuitive/discoverable part tho. Dunno how to solve properly, as indeed negative prompts are almost fundamental for v2 SD models to yield good stuff

**Review by patrickvonplaten — APPROVED** [review]
Thanks!

**Comment by radames** [comment]
thanks @Narsil , as long as the API support it we can now hack into the widget @mishig25 and add the syntax for a single input or two fields. Question @apolinario do all text-to-image models support negative prompt? since we only have on pipeline tag, we'll need to differentiate that for the widget

**Comment by Narsil** [comment]
> I think we could keep both.

I strongly disagree. Keeping two things open, means it's going to be exponentially harder to support new use cases.
I tend to prefer `::` for the potential to growing complexity to lpw.

Discoverability, as long as we have a single widget for all is going to be an issue (I can't imagine lpw being solved by a widget and not using regexps within the original text).

**Comment by radames** [comment]
have no strong opinions here, but I'd say the API should match the diffusers parameters, like the other APIi inference transformers endpoints. Maybe the `::` pattern should be added direct to `diffusers` WDYT @patrickvonplaten ?

**Comment by Narsil** [comment]
@apolinario Are we ok with just using `::` instead of the parameter ?

Seems the most versatile approach and we've postponed merging this for way too long imo.

**Comment by patrickvonplaten** [comment]
I'm not too keen on adding `::` logic to `diffusers` that's something that could be added on top of `diffusers`

**Comment by Narsil** [comment]
> I'm not too keen on adding `::` logic to `diffusers` that's something that could be added on top of `diffusers`

That's 100% understandable, but since this is visible as the API, it might come off as expected. 
Otherwise let's merge as-is, never implement `::` and just hopefully never have to merge lpw on the widgets.

**Pull request merged**
