### PR TITLE
Trigger CD ?

### PR DESCRIPTION
**Pull request by Narsil**
Somehow the old PR didn't trigger the CD (I'm guessing we should have rebased for the GH action to be visible :( )

### CODE REVIEW

**Comment by osanseviero** [comment]
Nope, we have a typo (sending a fix)

**Comment by osanseviero** [comment]
https://github.com/huggingface/api-inference-community/pull/130

**Comment by Narsil** [comment]
@osanseviero Can you review so we can trigger CD ?

**Review by osanseviero — APPROVED** [review]
LG

**Pull request merged**
