### PR TITLE
Refactor file structure

### PR DESCRIPTION
**Pull request by Kadermiyanyedi**
I added constants.py file and move all const variable to this file. Also, I added utils file and move helper functions to this file.  It will be more readable code structure.

Although there is a normalizers.py file, some normalize functions were in validation.py. I also moved these to the normalizer.py file.

### CODE REVIEW

**Comment by Kadermiyanyedi** [comment]
@Narsil Hi, I refactored some files to make the code more readable.  Can you review this PR? I look forward to your return :) :)

**Comment by Narsil** [comment]
Hi thanks for the PR.

Sorry, but what kind of problem are you trying to solve ?

**Comment by Kadermiyanyedi** [comment]
Hi, this PR is not solve specific problem directly.

I created a new file named constants.py to house constant variables, which helps to organize and centralize the management of these constants. This change enhances code readability, reduces redundancy, and simplifies maintenance by keeping all constant values in one dedicated location.

Also, I relocated certain normalization functions to the designated "normalize.py" file from their previous scattered locations. This streamlines the codebase by consolidating all normalization-related logic in one cohesive file. This change minimizes confusion, improves maintainability, and ensures that the normalization functions are easily accessible and consistently applied throughout the project.

**Comment by Kadermiyanyedi** [comment]
I added a new file "utils.py" to house helper functions, although I'm open to suggestions for a better file name. 

I made these changes to improve code readability and maintainability. By centralizing constants in the "constants.py" file, consolidating normalization functions in "normalize.py," and creating a "utils.py" file for helper functions, I aimed to enhance the overall organization of the codebase. This approach makes it easier for developers to locate and understand specific functionalities, leading to better collaboration and smoother maintenance of the project over time :) :)

**Comment by Narsil** [comment]
Hi I highly appreciate the effort, but I am the one maintaining this, and I tend to not modify code if there's not a specific problem we're trying to address.

If you do want to make contributions, please try to open an issue so we can discuss this earlier. I feel bad refusing most likely good work, but I just don't have the bandwidth to give it enough time for review, and it's not fixing a direct issue.
Although this repo is unlikely to receive any kind of change which is not the direct consequence of adding a feature or fixing a bug.

**Pull request closed without merging**
